package me.learning.api_schema.route.inline

import io.github.smiley4.ktoropenapi.post
import io.ktor.server.routing.Route
import io.ktor.server.routing.RoutingRequest
import me.learning.api_schema.common.MethodEnum
import me.learning.api_schema.extension.auth
import me.learning.api_schema.extension.ok
import me.learning.api_schema.core.schemaBuilder
import me.learning.api_schema.dto.handler.throwOnFileOrListTypeReqBody
import me.learning.api_schema.dto.request.FileInfoReq
import me.learning.api_schema.extension.getFileRequest
import me.learning.api_schema.extension.getFileDataRequest

// ================================================================================================================ //
// ================================================================================================================ //
// =====================                                                              ============================= //
// =====================                    BLOCK POST WITH FILE                      ============================= //
// ===================== to check local storage: System.getProperty("java.io.tmpdir") ============================= //
// =====================                                                              ============================= //
// ================================================================================================================ //
// ================================================================================================================ //


/**
 * Defines a POST route to handle file upload requests and process the uploaded file with the specified logic.
 *
 * The uploaded file is validated based on its extensions and passed to the provided processing block.
 * Optionally, the file can be deleted after processing is completed.
 *
 * @param T The type of the response generated by the processing block.
 * @param path The path for the POST route. Default is an empty string.
 * @param extensions The list of allowed file extensions for the uploaded file. Default is an empty list, meaning all extensions are allowed.
 * @param deleteAfterFinish Whether to delete the uploaded file after the processing block is completed. Default is false.
 * @param block A suspend lambda function to process the uploaded file. It receives a `FileInfoReq` object representing the file
 *               and produces a result of type `T`.
 * @return The configured Route.
 */
@JvmName("POST_FileInfoReq")
inline fun <reified T> Route.POSTFILE(
    path: String = "",
    extensions: List<String> = emptyList(),
    deleteAfterFinish: Boolean = false,
    crossinline block: suspend RoutingRequest.(file: FileInfoReq) -> T
): Route {
    val builder = schemaBuilder<T>(bodyAsFormData = true)

    return this.post(path, builder) {
        val request = call.getFileRequest(false, extensions).first()
        call.ok(call.request.block(request))
        if (deleteAfterFinish) request.file.delete()
    }
}


/**
 * Defines a POST route for handling file uploads with authorization and custom logic.
 * The route processes a multipart form-data request, extracts the uploaded file with validation,
 * invokes the provided logic block, and returns a response.
 *
 * @param T The type of the response to be returned by the route.
 * @param I The type of the authorization data required for the route.
 * @param path The URI path at which the route will be registered. Defaults to an empty string,
 * meaning the route will be registered at the current path.
 * @param extensions A list of allowed file extensions for the upload. If empty, all file types are allowed.
 * @param deleteAfterFinish A flag indicating whether the uploaded file should be deleted after the route processing is complete.
 * Defaults to false, meaning the file will not be deleted.
 * @param block A suspending lambda function representing the custom processing logic for the uploaded file.
 * It takes the authorization data and the uploaded file information as arguments and returns a response of type T.
 * @return The configured Route object.
 */
@JvmName("POST_Auth_FileInfoReq")
inline fun <reified T, reified I : Any> Route.POSTFILE(
    path: String = "",
    extensions: List<String> = emptyList(),
    deleteAfterFinish: Boolean = false,
    crossinline block: suspend RoutingRequest.(auth: I, file: FileInfoReq) -> T
): Route {
    val builder = schemaBuilder<T>(bodyAsFormData = true)

    return this.post(path, builder) {
        val auth = call.auth<I>()
        val request = call.getFileRequest(false, extensions).first()
        call.ok(call.request.block(auth, request))
        if (deleteAfterFinish) request.file.delete()
    }
}


/**
 * Defines a route that handles file uploads via HTTP POST and processes them as a list of `FileInfoReq`.
 *
 * @param T The type of the response returned by the provided `block`.
 * @param path The URL path on which the POST route will be defined. Defaults to an empty string, indicating the root.
 * @param extensions A list of allowed file extensions. Files with extensions not in this list will be rejected. Defaults to an empty list, allowing all extensions.
 * @param deleteAfterFinish Indicates whether the uploaded files should be automatically deleted after they are processed. Defaults to `false`.
 * @param block A suspendable lambda that processes the list of uploaded files (`FileInfoReq`) and returns a response of type `T`.
 * @return The configured `Route` for this POST operation.
 */
@JvmName("POST_List<FileInfoReq>")
inline fun <reified T> Route.POSTFILES(
    path: String = "",
    extensions: List<String> = emptyList(),
    deleteAfterFinish: Boolean = false,
    crossinline block: suspend RoutingRequest.(files: List<FileInfoReq>) -> T
): Route {
    val builder = schemaBuilder<T>(bodyAsFormData = true, bodyFileAsList = true)

    return this.post(path, builder) {
        val request = call.getFileRequest(true, extensions)
        call.ok(call.request.block(request))
        if (deleteAfterFinish) request.forEach { it.file.delete() }
    }
}


/**
 * Defines a POST route that accepts file uploads along with authentication and processes the uploaded files.
 *
 * @param path The relative path for the route. Default is an empty string, indicating the root level under the parent route.
 * @param extensions A list of allowed file extensions for the uploaded files. Defaults to an empty list, allowing all extensions.
 * @param deleteAfterFinish Whether to delete the uploaded files from the server storage after successfully processing them. Default is false.
 * @param block The handling logic for processing the authenticated user and uploaded file information.
 * It provides an authenticated object of type `I` and a list of uploaded files as `FileInfoReq` and returns a response of type `T`.
 * @return The configured route for this POST operation.
 */
@JvmName("POST_Auth_List<FileInfoReq>")
inline fun <reified T, reified I : Any> Route.POSTFILES(
    path: String = "",
    extensions: List<String> = emptyList(),
    deleteAfterFinish: Boolean = false,
    crossinline block: suspend RoutingRequest.(auth: I, files: List<FileInfoReq>) -> T
): Route {
    val builder = schemaBuilder<T>(bodyAsFormData = true, bodyFileAsList = true)

    return this.post(path, builder) {
        val auth = call.auth<I>()
        val request = call.getFileRequest(true, extensions)
        call.ok(call.request.block(auth, request))
        if (deleteAfterFinish) request.forEach { it.file.delete() }
    }
}


/**
 * Defines a HTTP POST route that accepts a file upload and a data payload, processes them, and executes
 * a custom action defined by the user.
 *
 * @param T The type of the returned response from the lambda block.
 * @param I The type of the additional data payload received in the form-data request.
 * @param path The path of the route (endpoint) where this method applies. Default is an empty string.
 * @param extensions A list of file extensions allowed for the uploaded files. Default is an empty list.
 * @param deleteAfterFinish Whether to delete the uploaded files from the server after the processing is completed.
 * Default is false.
 * @param block A lambda function that handles the received file and data payload. It receives the uploaded
 * file (`FileInfoReq`) and deserialized payload of type `I` as parameters and returns a value of type `T`.
 * @return The configured `Route` object for the specified endpoint.
 */
@JvmName("POST_FileInfoReq_Data")
inline fun <reified T, reified I> Route.POSTFILE(
    path: String = "",
    extensions: List<String> = emptyList(),
    deleteAfterFinish: Boolean = false,
    crossinline block: suspend RoutingRequest.(file: FileInfoReq, data: I) -> T
): Route {
    MethodEnum.POST.throwOnFileOrListTypeReqBody<I>(path)
    val builder = schemaBuilder<T>(bodyAsFormData = true, bodyFileAsList = true)

    return this.post(path, builder) {
        val (files, request) = call.getFileDataRequest<I>(false, extensions)
        call.ok(call.request.block(files.first(), request))
        if (deleteAfterFinish) files.forEach { it.file.delete() }
    }
}


/**
 * Defines a POST endpoint that handles multipart file uploads along with additional form data.
 *
 * This method is used to process incoming multipart form-data requests, which may include one or more files
 * and additional JSON-formatted data in the form part of the request. The request also supports authentication,
 * and provides automatic validation and response mechanisms for the uploaded data.
 *
 * Files can be validated for extensions and are optionally removed from the server's storage after the response
 * is generated. The endpoint implementation is defined using a callback block containing the authentication
 * object, file data, and additional data.
 *
 * @param path The route path where the POST request is handled. Defaults to an empty string.
 * @param extensions A list of permissible file extensions for uploaded files. Defaults to an empty list (no restriction).
 * @param deleteAfterFinish Indicates whether the uploaded files should be deleted from the server's storage after processing. Defaults to false.
 * @param block A suspendable lambda to process the request, which is provided with the authentication object, file metadata, and request data.
 * @return The configured Route for the POST request.
 */
@JvmName("POST_Auth_FileInfoReq_Data")
inline fun <reified T, reified I : Any, reified J> Route.POSTFILE(
    path: String = "",
    extensions: List<String> = emptyList(),
    deleteAfterFinish: Boolean = false,
    crossinline block: suspend RoutingRequest.(auth: I, file: FileInfoReq, data: J) -> T
): Route {
    MethodEnum.POST.throwOnFileOrListTypeReqBody<J>(path)
    val builder = schemaBuilder<T>(bodyAsFormData = true, bodyFileAsList = true)

    return this.post(path, builder) {
        val auth = call.auth<I>()
        val (files, data) = call.getFileDataRequest<J>(false, extensions)
        call.ok(call.request.block(auth, files.first(), data))
        if (deleteAfterFinish) files.forEach { it.file.delete() }
    }
}


/**
 *
 */
@JvmName("POST_FilesInfoReq_Data")
inline fun <reified T, reified I> Route.POSTFILES(
    path: String = "",
    extensions: List<String> = emptyList(),
    deleteAfterFinish: Boolean = false,
    crossinline block: suspend RoutingRequest.(files: List<FileInfoReq>, data: I) -> T
): Route {
    MethodEnum.POST.throwOnFileOrListTypeReqBody<I>(path)
    val builder = schemaBuilder<T>(bodyAsFormData = true, bodyFileAsList = true)

    return this.post(path, builder) {
        val (files, data) = call.getFileDataRequest<I>(true, extensions)
        call.ok(call.request.block(files, data))
        if (deleteAfterFinish) files.forEach { it.file.delete() }
    }
}


/**
 * Handles HTTP POST requests with multipart form-data, allowing authentication, uploading multiple files,
 * and sending additional data in the request body. This method invokes a custom block of code to process
 * the authenticated user, uploaded files, and request data.
 *
 * @param path The route path where the POST method will be applied. Default is an empty string.
 * @param extensions A list of allowed file extensions for uploaded files. Default is an empty list.
 * @param deleteAfterFinish Specifies whether to delete the uploaded files after processing. Default is false.
 * @param block A suspendable lambda that processes the authenticated user, list of uploaded files,
 *              and additional request data, and returns a response.
 *              - `auth`: The authenticated user object of type `I`.
 *              - `files`: A list of uploaded files represented by `FileInfoReq`.
 *              - `data`: Additional data of type `J` provided in the request body.
 * @return The configured Route instance with the defined POST endpoint.
 */
@JvmName("POST_Auth_FilesInfoReq_Data")
inline fun <reified T, reified I : Any, reified J> Route.POSTFILES(
    path: String = "",
    extensions: List<String> = emptyList(),
    deleteAfterFinish: Boolean = false,
    crossinline block: suspend RoutingRequest.(auth: I, files: List<FileInfoReq>, data: J) -> T
): Route {
    MethodEnum.POST.throwOnFileOrListTypeReqBody<J>(path)
    val builder = schemaBuilder<T>(bodyAsFormData = true, bodyFileAsList = true)

    return this.post(path, builder) {
        val auth = call.auth<I>()
        val (files, data) = call.getFileDataRequest<J>(true, extensions)
        call.ok(call.request.block(auth, files, data))
        if (deleteAfterFinish) files.forEach { it.file.delete() }
    }
}
